services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - STRIPE_KEY=${STRIPE_KEY}
    volumes:
      - .:/app
    working_dir: /app